#!/bin/bash
#cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
rm release/*
#cp pack.mcmeta pack_template.mcmeta
#cp pack_template.mcmeta pack.mcmeta
#sed -i sed -i '' "s/%PACK_FORMAT%/7/g" pack.mcmeta
zip -r release/2d-block-item-resourcepack-$(cat PACK_VERSION)-1.19.3.zip assets pack.png pack.mcmeta -x '*.DS_Store'
#rm pack.mcmeta
#mv pack_template.mcmeta pack.mcmeta
