#!/bin/bash
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
rm Release/*zip
cp pack.mcmeta pack_template.mcmeta
sed "s/%VERSION%/$(cat VERSION)/" pack_template.mcmeta > pack.mcmeta
zip -r Release/peek-flat-resource-pack-$(cat VERSION).zip assets pack.png pack.txt readme.txt pack.mcmeta respackopts.json5 -x '*.DS_Store'
rm pack.mcmeta
mv pack_template.mcmeta pack.mcmeta
